### PR TITLE
Bug Fix

### LINKED ISSUE #309: explore page empty state has two btns which act the same
**Describe the bug**
empty state of explore page have a btn and a fab

**Expected behavior**
in empty state we need to show only btn
and when not empty we need to show only FAB

**Screenshots**
image

### LINKED ISSUE #325: add a btn which redirects user to faq page(refer image)
image

### PR DESCRIPTION
**Pull request by Manas1820**
# Description

Please include the summary of the change as well as the issue that is fixed (if applicable). Also if any dependencies that are required for this change to work.

Fixes #309 
Fixes #325

## Type of change

Please choose the relavant type of change.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Also summarise the process for us to reproduce.

- [x] Test A: checked through my emulator.
- [ ] Test B: Firebase testing labs
- [ ] Test C: Test through flutter test code
- [ ] Test D: Other (Please specify)

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this application
- [x] I have checked the code working on my emulator
- [ ] I have commented my code for better understanding
- [ ] These changes generate no new warnings
- [ ] These changes do not effect the existing functionalities,

### CODE REVIEW

File: lib/view/teams/teaminfo.dart [hunk 1]
```diff
@@ -560,22 +560,23 @@ confirmationPopup(
...
       desc:
-          "Please read the requirmnets for a verified team before applying for verifications. Our team will be in contact with you via email for any queries",
+          "Please read the requirements for a verified team before applying for verifications. Our team will be in contact with you via email for any queries",
       buttons: [
         DialogButton(
           child: Padding(
             padding: const EdgeInsets.all(8.0),
             child: Text(
-              "Close",
+              "Info",
```
Comment (hayat-tamboli) [inline lib/view/teams/teaminfo.dart]: Please change this to read more

**Review by hayat-tamboli — APPROVED** [review]
